CREATE ROLE gateway_user WITH LOGIN PASSWORD 'Aa12345aA!'
    INHERIT
    CONNECTION LIMIT -1
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION ;
CREATE DATABASE gateway
    WITH OWNER = gateway_user
        ENCODING = 'UTF8'
        TABLESPACE = pg_default
        CONNECTION LIMIT = -1
        LC_COLLATE='en_US.UTF-8'
        LC_CTYPE='en_US.UTF-8'
        TEMPLATE template0;
\c gateway
CREATE EXTENSION IF NOT EXISTS pgcrypto;